name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hyiik09/assignment3:latest
      
    - name: Push the Docker image
      run: docker login -u hyiik09 -p ${{ secrets.DOCKER_TOKEN }} && docker push hyiik09/assignment3:latest
