name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Publish to GitHub Packages
      uses: docker/build-pus-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/next
        tags: latest, ${{ github.run_number }}
    
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hyiik09/assignment3
        tags: latest, ${{ github.run_number }}
